name 'all_systems'
maintainer 'James Massardo'
maintainer_email 'james@dxrf.com'
license 'Apache-2.0'
description 'Installs/Configures all_systems'
version '0.2.30'
depends 'chef-client'
depends 'audit'
depends 'cis-baseline'
issues_url 'https://github.com/jmassardo/all_systems/issues'
source_url 'https://github.com/jmassardo/all_systems'
